seed: &seed 0
max_steps: 10_000
start_training_after: 3_000
log_every: 500

environment:
  _target_: gymnasium.make
  id: Hopper-v4
  render_mode: human

replay_buffer:
  _target_: flashbax.make_item_buffer
  max_length: 4_000
  min_length: 3_000
  sample_batch_size: 1024
  add_batches: False
  
agent:
  _target_: experts.sac_agent.SACAgent
  seed: *seed
  actor_module_config:
    _target_: networks.policy.NormalTanhPolicy
    hidden_dims: [64, 64, 64]
  critic_module_config:
    _target_: networks.critic.Critic
    hidden_dims: [64, 64, 64]
  value_critic_module_config:
    _target_: networks.critic.ValueCritic
    hidden_dims: [64, 64, 64]