env_name: &env_name Hopper-v4
# env_name: &env_name HalfCheetah-v5
seed: &seed 0
n_iters_collect_buffer: &n_iters_collect_buffer 5_000
n_iters_training: 100_000
store_random_buffer: True
log_every: 500
eval_every: 500

environment:
  _target_: gymnasium.wrappers.TimeLimit
  max_episode_steps: 1000
  env:
      _target_: gymnasium.make
      id: *env_name
      render_mode: human

evaluation:
  num_episodes: 5
  environment:
    _target_: gymnasium.wrappers.TimeLimit
    max_episode_steps: 1000
    env:
        _target_: gymnasium.make
        id: *env_name
        # render_mode: human

replay_buffer:
  _target_: flashbax.make_item_buffer
  max_length: 1_000_000
  min_length: *n_iters_collect_buffer
  sample_batch_size: 256
  add_batches: False

agent:
  _target_: experts.sac_agent.SACAgent
  seed: *seed
  actor_module_config:
    _target_: networks.policy.NormalTanhPolicy
    hidden_dims: [256, 256]
  critic_module_config:
    _target_: networks.critic.Critic
    hidden_dims: [256, 256]
  temperature_module_config:
    _target_: networks.extra.Temperature
    initial_temperature: 1.0
