env_name: &env_name Hopper-v4
seed: &seed 0
n_iters_collect_buffer: &n_iters_collect_buffer 5_000
n_iters_training: 1_000_000
store_random_buffer: False
log_every: 1_000
eval_every: 1_000

evaluation:
  num_episodes: 10

environment:
  _target_: gymnasium.wrappers.NormalizeReward
  env:
    _target_: gymnasium.make
    id: *env_name
    render_mode: human

replay_buffer:
  _target_: flashbax.make_item_buffer
  max_length: 1_000_000
  min_length: *n_iters_collect_buffer
  sample_batch_size: 256
  add_batches: False
  
agent:
  _target_: experts.sac_agent.SACAgent
  seed: *seed
  actor_lr: 3e-4
  critic_lr: 1e-3
  actor_module_config:
    _target_: networks.policy.NormalTanhPolicy
    hidden_dims: [256, 256]
  critic_module_config:
    _target_: networks.critic.Critic
    hidden_dims: [256, 256]
  value_critic_module_config:
    _target_: networks.critic.ValueCritic
    hidden_dims: [256, 256]