seed: 0
env_name: HalfCheetah-v5
n_iters_training: 1000000
batch_size: 2048
precollect_buffer_size: 5000
log_every: 1000
eval_every: 5000
save_every: 5000
environment:
  _target_: gymnasium.wrappers.TimeLimit
  max_episode_steps: 1000
  env:
    _target_: gymnasium.make
    id: HalfCheetah-v5
replay_buffer:
  _target_: utils.instantiate_jitted_fbx_buffer
  fbx_buffer_config:
    _target_: flashbax.make_item_buffer
    max_length: 1000000
    min_length: 5000
    sample_batch_size: 2048
    add_batches: false
agent:
  _target_: agents.gail.GAILAgent.create
  seed: 0
  batch_size: 2048
  source_expert_buffer_state_path: agents/experts/HalfCheetah-v5/config/collected_rollouts/buffer_state.pickle
  agent_config:
    _target_: agents.sac.SACAgent.create
    actor_module_config:
      _target_: agents.sac.networks.NormalTanhPolicy
      hidden_dims:
      - 256
      - 256
    critic_module_config:
      _target_: agents.sac.networks.Critic
      hidden_dims:
      - 256
      - 256
    temperature_module_config:
      _target_: agents.sac.networks.Temperature
      initial_temperature: 0.2
    actor_optimizer_config:
      transforms:
      - _target_: optax.clip
        max_delta: 1.0
      - _target_: optax.adam
        learning_rate: 0.0003
    critic_optimizer_config:
      transforms:
      - _target_: optax.clip
        max_delta: 1.0
      - _target_: optax.adam
        learning_rate: 0.0003
    temperature_optimizer_config:
      transforms:
      - _target_: optax.sgd
        learning_rate: 0.0
  policy_discriminator_config:
    _target_: agents.gail.GAILDiscriminator.create
    module_config:
      _target_: nn.networks.MLP
      hidden_dims:
      - 256
      - 256
      out_dim: 1
      squeeze: true
    optimizer_config:
      transforms:
      - _target_: optax.clip
        max_delta: 1.0
      - _target_: optax.adam
        learning_rate: 0.0003
    loss_config:
      _target_: misc.gan.losses.SoftplusLoss
      is_generator: false
    reward_transform_config:
      _target_: agents.gail.reward_transforms.RewardStandartization.create
evaluation:
  seed: 42
  num_episodes: 25
  environment:
    _target_: gymnasium.wrappers.TimeLimit
    max_episode_steps: 1000
    env:
      _target_: gymnasium.make
      id: HalfCheetah-v5
