seed: &seed 0
log_every: 1_000

batch_size: 256

n_training_iters: 20_000

enot:
  _target_: misc.enot.enot.ENOT.create
  seed: *seed
  target_weight: 5.
  transport_module_config:
    _target_: nn.networks.MLP
    n_blocks: 4
    hidden_dim: 128
  transport_optimizer_config: &optimizer_config
    transforms:
      - _target_: optax.clip
        max_delta: 1.0
      - _target_: optax.adam
        learning_rate: 3e-4
  transport_loss_fn_config:
    _target_: hydra.utils.get_method
    path: misc.enot.losses.transport_loss
  g_potential_module_config:
    _target_: nn.networks.MLP
    n_blocks: 4
    hidden_dim: 128
  g_potential_optimizer_config: *optimizer_config
  g_potential_loss_fn_config:
    _target_: hydra.utils.get_method
    path: misc.enot.losses.g_potential_loss
