_constants:
  target_learner_lr: &tl_lr 1e-4
  source_learner_lr: &sl_lr 3e-4 # Must be better than target learner
  gan_loss: &gan_loss misc.gan.losses.SoftplusLoss

agent:
  # Target Agent
  target_learner_config:
    _target_: agents.sac.SACAgent.create
    actor_module_config:
      _target_: agents.sac.networks.NormalTanhPolicy
      model_type: MLP 
      n_blocks: 2
      hidden_dim: 256
    critic_module_config:
      _target_: agents.sac.networks.Critic
      model_type: MLP
      n_blocks: 2
      hidden_dim: 256
    temperature_module_config:
      _target_: agents.sac.networks.Temperature
      initial_temperature: 0.2
    actor_optimizer_config: &target_optimizer_config
      transforms:
        - _target_: optax.clip
          max_delta: 1.0
        - _target_: optax.adam
          learning_rate: *tl_lr
    critic_optimizer_config: *target_optimizer_config
    temperature_optimizer_config:
      transforms:
        - _target_: optax.sgd
          learning_rate: 0.
  target_gail_discriminator_config:
    _target_: agents.gail.GAILDiscriminator.create
    module_config:
      _target_: nn.networks.MLP
      n_blocks: 2
      hidden_dim: 256
      out_dim: 1
      squeeze: True
    optimizer_config: *target_optimizer_config
    loss_config:
      _target_: *gan_loss
      is_generator: False
    reward_transform_config:
      _target_: agents.gail.gail_discriminator.reward_transforms.RewardStandartization.create
  # Source Agent
  source_learner_config:
    _target_: agents.sac.SACAgent.create
    actor_module_config:
      _target_: agents.sac.networks.NormalTanhPolicy
      model_type: MLP 
      n_blocks: 2
      hidden_dim: 256
    critic_module_config:
      _target_: agents.sac.networks.Critic
      model_type: MLP
      n_blocks: 2
      hidden_dim: 256
    temperature_module_config:
      _target_: agents.sac.networks.Temperature
      initial_temperature: 1.0
    actor_optimizer_config: &source_optimizer_config
      transforms:
        - _target_: optax.clip
          max_delta: 1.0
        - _target_: optax.adam
          learning_rate: *sl_lr
    critic_optimizer_config: *source_optimizer_config
    temperature_optimizer_config:
      transforms:
        - _target_: optax.sgd
          learning_rate: 1e-5
  source_gail_discriminator_config:
    _target_: agents.gail.GAILDiscriminator.create
    module_config:
      _target_: nn.networks.MLP
      n_blocks: 2
      hidden_dim: 256
      out_dim: 1
      squeeze: True
    optimizer_config: *source_optimizer_config
    loss_config:
      _target_: *gan_loss
      is_generator: False
    reward_transform_config:
      _target_: agents.gail.gail_discriminator.reward_transforms.RewardStandartization.create
