agent:
  target_learner_config: &sac_config
    _target_: agents.sac.SACAgent.create
    actor_module_config:
      _target_: agents.sac.networks.NormalTanhPolicy
      model_type: MLP 
      n_blocks: 2
      hidden_dim: 256
    critic_module_config:
      _target_: agents.sac.networks.Critic
      model_type: MLP
      n_blocks: 2
      hidden_dim: 256
    temperature_module_config:
      _target_: agents.sac.networks.Temperature
      initial_temperature: 0.2
    actor_optimizer_config: &optimizer_config
      transforms:
        - _target_: optax.clip
          max_delta: 1.0
        - _target_: optax.adam
          learning_rate: 3e-4
    critic_optimizer_config: *optimizer_config
    temperature_optimizer_config:
      transforms:
        - _target_: optax.sgd
          learning_rate: 0.
  source_learner_config: *sac_config
