seed: &seed 42
n_training_iters: 30_000
batch_size: 128
eval_batch_size: 512
log_every: 500
eval_every: 500

dataset:
  size: 20_000
  mu: [1, 2, 4]
  sigma: [1, 1, 3]

gan:
  _target_: gan.gan.GAN.create
  seed: *seed
  generator_config:
    module_config:
      _target_: networks.common.MLP
      hidden_dims: [256, 256]
    optimizer_config:
      transforms:
        - _target_: optax.clip
          max_delta: 1.0
        - _target_: optax.adamw
          learning_rate: 3e-4
  discriminator_config:
    gradient_penalty_coef: 10
    module_config:
      _target_: networks.discriminator.Discriminator
      hidden_dims: [256, 256]
    optimizer_config:
      transforms:
        - _target_: optax.clip
          max_delta: 1.0
        - _target_: optax.adamw
          learning_rate: 3e-4
