seed: &seed 42
env_name: &env_name HalfCheetah-v5 # Hopper-v5
precollect_buffer_size: &precollect_buffer_size 5_000
n_iters_training: 1_000_000

log_every: 500
eval_every: 1_000
save_every: 1_000

environment:
  _target_: gymnasium.wrappers.TimeLimit
  max_episode_steps: 1000
  env:
      _target_: gymnasium.make
      id: *env_name
      render_mode: human

replay_buffer:
  _target_: flashbax.make_item_buffer
  max_length: 1_000_000
  min_length: *precollect_buffer_size
  sample_batch_size: &batch_size 256
  add_batches: False

agent:
  _target_: agents.dida.DIDAAgent.create
  seed: *seed
  encoders_dim: 6
  expert_batch_size: *batch_size
  expert_buffer_state_path: archive/agents/sac/HalfCheetah-v5/collected_rollouts/buffer_state.pickle
  agent_config:
    _target_: agents.sac.SACAgent.create
    actor_module_config:
      _target_: networks.policy.NormalTanhPolicy
      hidden_dims: [256, 256]
    critic_module_config:
      _target_: networks.critic.Critic
      hidden_dims: [256, 256]
    temperature_module_config:
      _target_: agents.sac.Temperature
      initial_temperature: 0.5
    actor_optimizer_config: &optimizer_config
      transforms:
        - _target_: optax.clip
          max_delta: 1.0
        - _target_: optax.adamw
          learning_rate: 3e-4
    critic_optimizer_config: *optimizer_config
    temperature_optimizer_config:
      transforms:
        - _target_: optax.sgd
          learning_rate: 1e-5
  discriminator_config:
    _target_: agents.gail.GAILDiscriminator.create
    module_config:
      _target_: networks.discriminator.Discriminator
      hidden_dims: [256, 256]
    optimizer_config: *optimizer_config
    gradient_penalty_coef: 10.
    reward_transform_config:
      _target_: agents.gail.reward_transforms.RewardStandartization.create
  learner_encoder_config:
    _target_: gan.generator.Generator.create
    module_config:
      _target_: networks.common.MLP
      hidden_dims: [128, 128]
    optimizer_config: *optimizer_config
  expert_encoder_config:
    _target_: gan.generator.Generator.create
    module_config:
      _target_: networks.common.MLP
      hidden_dims: [128, 128]
    optimizer_config: *optimizer_config
  domain_discriminator_config:
    _target_: gan.discriminator.Discriminator.create
    module_config:
      _target_: networks.discriminator.Discriminator
      hidden_dims: [256, 256]
    optimizer_config: *optimizer_config
    gradient_penalty_coef: 10.

evaluation:
  seed: 42
  num_episodes: 10
  environment:
    _target_: gymnasium.wrappers.TimeLimit
    max_episode_steps: 1000
    env:
        _target_: gymnasium.make
        id: *env_name

archive:
  agent_load_dir: &agent_dir archive/agents/dida
  agent_save_dir: *agent_dir
  agent_buffer_load_dir: *agent_dir
  agent_buffer_save_dir: *agent_dir
  random_buffer_load_dir: &random_buffer_dir archive/random_buffers
  random_buffer_save_dir: *random_buffer_dir
