seed: &seed 0
env_name: &env_name Hopper-v5

n_iters_training: 1_000_000
batch_size: &batch_size 2048

precollect_buffer_size: &precollect_buffer_size 5_000

log_every: 1000
eval_every: 10_000
save_every: 10_000

environment:
  _target_: gymnasium.wrappers.TimeLimit
  max_episode_steps: 1000
  env:
      _target_: gymnasium.make
      id: *env_name

replay_buffer:
  _target_: utils.utils.instantiate_jitted_fbx_buffer
  fbx_buffer_config:
    _target_: flashbax.make_item_buffer
    max_length: 1_000_000
    min_length: *precollect_buffer_size
    sample_batch_size: *batch_size
    add_batches: False

agent:
  _target_: agents.DIDAAgent.create
  seed: *seed
  encoder_dim: 11
  expert_batch_size: *batch_size
  expert_buffer_state_path: experts/Hopper-v5/archive/Hopper-v5/collected_rollouts/buffer_state.pickle
  n_domain_discriminator_updates: 5
  domain_loss_scale_fn_config:
    _target_: agents.dida.domain_loss_scale_fns.ConstantDomainLossScale
    domain_loss_scale: 0.3
  #
  use_das: False
  #
  agent_config:
    _target_: agents.SACAgent.create
    actor_module_config:
      _target_: networks.policy.NormalTanhPolicy
      hidden_dims: [128, 128]
    critic_module_config:
      _target_: networks.critic.Critic
      hidden_dims: [128, 128]
    temperature_module_config:
      _target_: agents.sac.Temperature
      initial_temperature: 0.2
    actor_optimizer_config: &optimizer_config
      transforms:
        - _target_: optax.clip
          max_delta: 1.0
        - _target_: optax.adamw
          learning_rate: 3e-4
    critic_optimizer_config: *optimizer_config
    temperature_optimizer_config:
      transforms:
        - _target_: optax.sgd
          learning_rate: 0.
  policy_discriminator_config:
    _target_: agents.gail.GAILDiscriminator.create
    module_config:
      _target_: networks.discriminator.Discriminator
      hidden_dims: [128, 128]
    optimizer_config: *optimizer_config
    loss_config:
      _target_: gan.losses.SoftplusLoss
      is_generator: False
    reward_transform_config:
      _target_: agents.gail.reward_transforms.RewardStandartization.create
  learner_encoder_config:
    _target_: gan.generator.Generator.create
    module_config:
      _target_: networks.common.MLP
      hidden_dims: [128, 128]
    optimizer_config: *optimizer_config
    loss_config:
      _target_: agents.dida.encoder_loss.DIDAEncoderLoss
  domain_discriminator_config:
    _target_: gan.discriminator.Discriminator.create
    module_config:
      _target_: networks.discriminator.Discriminator
      hidden_dims: [128, 128]
    optimizer_config: *optimizer_config
    loss_config:
      _target_: gan.losses.SoftplusLoss
      is_generator: False

evaluation:
  seed: 42
  num_episodes: 25
  environment:
    _target_: gymnasium.wrappers.TimeLimit
    max_episode_steps: 1000
    env:
        _target_: gymnasium.make
        id: *env_name
  extra_args:
    visualize_state_and_policy_scatterplots: True
    visualize_state_and_policy_histograms: True

archive:
  agent_load_dir: &agent_dir archive/agents/dida
  agent_save_dir: *agent_dir
  agent_buffer_load_dir: *agent_dir
  agent_buffer_save_dir: *agent_dir
  random_buffer_load_dir: &random_buffer_dir archive/random_buffers
  random_buffer_save_dir: *random_buffer_dir
