seed: &seed 0

n_iters_training: 2_000_000
batch_size: &batch_size 256

log_every: 1_000
eval_every: 5_000
save_every: 5_000

update_encoder_every: &update_encoder_every 2

model:
  _target_: agents.dida.InDomainEncoder.create
  seed: *seed
  encoding_dim: 2
  #
  target_batch_size: *batch_size
  target_random_buffer_state_path: ._tmp_archive_dir/random_buffers/ToyEnvTwoDim.pickle
  #
  source_batch_size: *batch_size
  source_expert_buffer_state_path: experts/ToyEnvOneDim/size10/collected_rollouts/buffer_state.pickle
  #
  update_encoder_every: *update_encoder_every
  #
  target_encoder_config:
    _target_: gan.generator.Generator.create
    module_config:
      _target_: networks.dida.AffineTransform
    optimizer_config:
      transforms:
        - _target_: optax.clip
          max_delta: 1.0
        - _target_: optax.adamw
          learning_rate: 3e-4
    loss_config:
      _target_: agents.imitation_learning.dida.domain_encoder.losses.InDomainEncoderLoss
      state_loss_scale: 0.2
  discriminators_config:
    _target_: agents.imitation_learning.dida.domain_encoder.DomainEncoderDiscriminators.create
    update_policy_discriminator_every: *update_encoder_every
    state_discriminator_config:
      _target_: gan.discriminator.Discriminator.create
      module_config:
        _target_: networks.discriminator.Discriminator
      optimizer_config:
        transforms:
          - _target_: optax.clip
            max_delta: 1.0
          - _target_: optax.adamw
            learning_rate: 3e-4
      loss_config:
        _target_: gan.losses.SoftplusLoss
        is_generator: False
    policy_discriminator_config:
      _target_: gan.discriminator.Discriminator.create
      module_config:
        _target_: networks.discriminator.Discriminator
      optimizer_config:
        transforms:
          - _target_: optax.clip
            max_delta: 1.0
          - _target_: optax.adamw
            learning_rate: 3e-4
      loss_config:
        _target_: gan.losses.SoftplusLoss
        is_generator: False

evaluate_extra_args:
  two_dim_data_plot_flag: True
